### ISSUE TITLE
Missing description of scenarios

### ISSUE THREAD

**Issue by senovsky** [wswebcreation/wdio-cucumberjs-json-reporter#18] opened 2019-11-13 14:41 UTC
**Environment:**
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **webdriver.io version:** 5.16.6
 - **@wdio/cucumber-framework version:** 5.16.6
 - **wdio-cucumberjs-json-reporter version:** 1.1.2

**Config of webdriver.io and the reporter**
See `wdio.conf.js` in my repository

**To Reproduce**
Clone my repository https://github.com/senovsky/cucumber-boilerplate and run those commands:
npm install
./edit-template.sh
npm test

**Describe the bug**
In `.tmp\report.html.json`, the descriptions of all scenarios are empty strings.

**Expected behavior**
I would like the descriptions of scenarios in my `.feature` files to be correctly copied into the `.json` file. So that they are then visible in the HTML report, see snapshot.

**Snapshots**
![wdio-cucumberjs-json-reporter_Missing_Desc](https://user-images.githubusercontent.com/49440120/68772842-cfa03e80-062a-11ea-8b2e-b548cb883b38.png)

**Comment by wswebcreation** [comment] 2019-11-17 06:49
Hi @senovsky 

This is not a bug in this report, but a missing feature in the `@wdio/cucumber-framework`, it's not exposing this data in the `@wdio/reporter` which I use. 
I don't have the time currently to investigate this, but maybe create an issue on the WebdriverIO project or maybe even better, create a PR there 😉 

I'm going to close it here for now, it's still open for discussion

**Closed by wswebcreation** 2019-11-17 06:49 UTC
