### ISSUE TITLE
TypeError: cucumberJson.attach is not a function

### ISSUE THREAD

**Issue by ania-s** [wswebcreation/wdio-cucumberjs-json-reporter#8] opened 2019-08-07 11:49 UTC
wdio-cucumberjs-json-reporter: 1.0.8

When trying to attach some custom data to the report by using:

```
import cucumberJson from 'wdio-cucumberjs-json-reporter';
cucumberJson.attach('just a string');
```

I get the following error: TypeError: cucumberJson.attach is not a function

**Comment by SDLarmo** [comment] 2019-08-21 11:26
Hi @ania-s .
You could try the following:
```
const cucumberJson = require('wdio-cucumberjs-json-reporter').default;
cucumberJson.attach('just a string');
```

**Comment by wswebcreation** [comment] 2019-08-22 09:01
@ania-s 

Hmm, are you using Babel to compile the code? In local demo project it just works

@SDLarmo 

Yes, that is the way to do it when you use the require

**Comment by wswebcreation** [comment] 2019-08-23 11:30
@ania-s 

I found the cause, this has to do with your babel setup. Please make sure you use the Babel setup which can be found [here](https://webdriver.io/docs/babel.html). Then you can use `import` statements.

Going to close it because it is not related to this module

**Closed by wswebcreation** 2019-08-23 11:30 UTC
Labels: needs more info

**Comment by ania-s** [comment] 2019-08-26 07:50
It works well with default in my case as @SDLarmo mentioned. Thank you both for checking it

**Comment by siddharthmittal97** [comment] 2022-11-26 14:34
Those who are facing issue . Do add .default after require("wdio-cucumberjs-json-reporter")

const cucumberJson = require("wdio-cucumberjs-json-reporter").default;
    afterScenario: async (world, result, context) => {
      await browser.takeScreenshot().then(async function (png) {
        await cucumberJson.attach(png, "image/png");
      });
      await browser.pause(1000);
    }
Thanks a lot @SDLarmo . Above code worked for me .
